import localFont from "next/font/local";
import "@/public/css/font-family.css";
import "@/public/css/main.css";
import "@/public/css/owl.carousel.min.css";
import "@/public/css/owl.theme.default.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
